# Generated by Django 3.1.4 on 2020-12-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
